name: CI/CD
on: [push]
jobs:
    Build: 
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/gestion_vuelosB'
        steps: 
            - uses: actions/checkout@v4
            - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV
            - name: "use node ${{ env.node_version }}"
              uses: actions/setup-node@v3
              with:
                node-version: "${{ env.node_version }}"
            - name: Install Dependencies
              run: yarn install
            - name: Build
              run: yarn build